### ISSUE TITLE
Enable backports to stretch

### ISSUE THREAD

**Issue by adefelicibus** [thehyve/cbioportal-docker#15]
Hi,
I tried to build the image and I got the error:

> E: The value 'jessie-backports' is invalid for APT::Default-Release as such a release is not available in the sources

I had to enable first the backports to stretch to be able to build the image.
`RUN echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/source.list`
and changed this
`&& apt-get install -y --no-install-recommends -t jessie-backports`
to this
`&& apt-get install -y --no-install-recommends -t stretch-backports`

Thanks

**Comment by fedde-s** [comment]
Looks like the OpenJDK base image updated its own base image to the new stable release of Debian. We should update the Dockerfile as well, thanks for reporting it!

The several layers of standard base images don't provide an easy way to explicitly pin the underlying OS to a guaranteed-compatible version as far as I can see, at least not without also blocking out security updates for all layers. Luckily it will take a while before this an issue again, as Debian only produces a new stable release about once every two years.

**Comment by fedde-s** [comment]
I removed the reference to the `jessie-backports` repository in 04ceb41616071b24324aaf27038e59608c0b185e, released to master.

**Comment by fedde-s** [comment]
The image builds successfully again, and all major features to get a server up and running (database migration, data validation and loading, and serving the query, study, Oncoprint and patient views) seem to work as expected.

**Comment by adefelicibus** [comment]
Thank you @fedde-s!
