### ISSUE TITLE
error database version

### ISSUE THREAD

**Issue by kcourtet** [thehyve/cbioportal-docker#46]

**Comment by kcourtet** [comment]
Hi ! I've got an error message when I try to import a study in the portal. It says that the database v2.7.2 is required, but it is exactly the release I'm using  (scheme and seed). Have you any explanations ?

Regards.

**Comment by Sjoerd-van-Hagen** [comment]
Hi,
What were the steps you followed?

**Comment by kcourtet** [comment]
I just found that I was not using the right portal.properties file with the metaImport script -> I followed all the indicated steps in the README to run a cBiportal server (on the latest version) but I was still using an old volume reference when importing data...

Thank for your support anyway !
