### ISSUE TITLE
Problem importing 2 samples under the same cancer study

### ISSUE THREAD

**Issue by lakhujanivijay** [thehyve/cbioportal-docker#52]
Hi,

I have 2 samples what I want to import mutation data (from vcf file - 1 / sample ) into local cbioportal under the same cancer study (same cancer study identifier).

So, first I import one sample from a folder structure like this
```
├── case_lists
│   └── cases_sequenced.txt
├── data_clinical_patient.txt
├── data_clinical_sample.txt
├── meta_clinical_patient.txt
├── meta_clinical_sample.txt
├── meta_study.txt
├── meta_mutation.txt
└── Sample1.maf

1 directory, 8 files
```
which is successful and then I upload the 2nd sample from a folder structure like this

```
├── case_lists
│   └── cases_sequenced.txt
├── data_clinical_patient.txt
├── data_clinical_sample.txt
├── meta_clinical_patient.txt
├── meta_clinical_sample.txt
├── meta_study.txt
├── meta_mutation.txt
└── Sample2.maf

1 directory, 8 files
```
***Notice the maf file names**

However, what happens is that the study is removed throwing this message and it replaces my sample1 with sample2

`Cancer study with identifier "demo" found in database, removing...`

which is not what I want, what I want is to have both of them under the same study.

So, how should I do that ? Any suggestions ? Should I do this first - 

- merge both the `vcf` files into a single `vcf` file
- convert the merged `vcf` file into `maf` using `vcf2maf`
- and then put the name of merged `maf` file in the `meta_mutation.txt` file
- and finally import it into cbioportal ?

**Comment by fedde-s** [comment]
The data for all samples of a study should be in listed in the same data files, within that study's one folder structure. In tab-separated files such as MAF and `data_clinical_*.txt` that can generally be done by just concatenating the lines of the files (without repeating the header); the samples are distinguished by a sample ID column. Case lists (and in rare cases some of the files with `meta` in their names) list sample IDs as a comma-separated list on a single line.

**Comment by fedde-s** [comment]
So yes; you'll need a merged MAF file, merged clinical data files and merged case list (sample list) files.

**Comment by lakhujanivijay** [comment]
@fedde-s  Thank you for your prompt response. That really helped. One last question about the case list file. My `cases_sequenced.txt` file (for multiple) looks like this

```
cancer_study_identifier: dh_trial3
stable_id: dh_trial3_sequenced	
case_list_name: Tumor Samples with sequenced data	
case_list_description: All tumors with sequenced data (1 sample)	
case_list_category: all_cases_with_mutation_data
case_list_ids: ab	jk	bc	cd	de	ef	fg	gh	hi	ij
```
Above, you said I need "merged case list". My case list file having tab separated sample names just works. Is it the correct format ?

**Comment by fedde-s** [comment]
Yes, sorry for mistakenly saying that it should be comma-separated; as described in [the docs](https://github.com/cBioPortal/cbioportal/blob/v2.1.0/docs/File-Formats.md#case-lists), a tab-separated list is the correct format.

**Comment by fedde-s** [comment]
Given that I just linked to the upstream cBioPortal repository, I believe this to be generic to the cBioPortal data loading pipeline, maintained and supported elsewhere ([here](https://github.com/cBioPortal/cbioportal) and [on the user discussion mailing list](http://groups.google.com/group/cbioportal), respectively). Do you see any further issue regarding the instructions this repository offers on how to use Docker to deploy it?

**Comment by lakhujanivijay** [comment]
@fedde-s Yeah, that indeed worked for me. Thanks. Indeed that is generic to cbioportal and I should not have posted that here; I'm sorry about that. That was it all. 

Cheers 
@lakhujanivijay  :+1:  :beer:
