### ISSUE TITLE
How to enable user authentication for local cbioportal instance installed using docker?

### ISSUE THREAD

**Issue by lakhujanivijay** [thehyve/cbioportal-docker#53]
Hi again!

So, I have finally setup cbioportal using docker and have successfully uploaded few studies. The next step I want is to set up user authentication into the local cbioportal instance. [I know it's feasible ](https://docs.cbioportal.org/2.2-authorization-and-authentication/user-authorization).

Where should I begin? Should I look at [this](https://cbioportal.readthedocs.io/en/latest/Customizing-your-instance-of-cBioPortal.html#cbioportal-documentation-settings) link to customize cbioportal

Can you please pin point me to the exact help page?

**Comment by fedde-s** [comment]
The way we usually implement this nowadays involves a separate Keycloak authentication service. Exactly how to set it up for your use-case may vary a bit, but we documented the basics of how to attach a Docker container for it [right in this repository](https://github.com/thehyve/cbioportal-docker/blob/v2.1.0/docs/using-keycloak.md).

**Comment by fedde-s** [comment]
The link to that from the [main README](https://github.com/thehyve/cbioportal-docker/blob/v2.1.0/README.md#data-loading--more-commands) does contain the word authentication. Do you think there's a findability issue there, or should this issue report be closed?

**Comment by lakhujanivijay** [comment]
Sorry, I actually wanted to reopen this case. The link that you have shared is good and in fact we have followed the steps point by point to get the authentication running, however, we have failed so far. What is the key information that you need from me (logs?) which can help you guys help me? How do I troubleshoot what went wrong.

I understand that without looking at the background information, it's hard for anyone; that's why let let me know what information could be sent here.

Looking forward to your response

Thanks

@lakhujanivijay

**Comment by Sjoerd-van-Hagen** [comment]
Hi @lakhujanivijay,

For questions, please do not open issues but post on the Google group (https://groups.google.com/forum/#!forum/cbioportal).
