### ISSUE TITLE
How to get rid off the cbioportal logo on the local instance of cbioportal ?

### ISSUE THREAD

**Issue by lakhujanivijay** [thehyve/cbioportal-docker#54]
Hi,

Is it possible to get rid off the cBioportal image on the left hand side?

![local cbioportal](https://github.com/lakhujanivijay/Random_images_for_issues/blob/master/Screenshot%20from%202019-04-24%2017-21-04.png?raw=true)

If yes :

1. How to do that ?
2. And then how to add a new image there ? Is there a flag which I could change in the `portal.properties` file?

**Comment by fedde-s** [comment]
I don't think that's a documented feature of cBioPortal. If you can't find it in the cBioPortal documentation linked in [the instructions here](https://github.com/thehyve/cbioportal-docker/blob/v2.1.0/README.md#step-6---run-the-cbioportal-web-server), it might be worth sending your question to the [public mailing list for users of the cBioPortal platform](http://groups.google.com/group/cbioportal).

Do you see any issue in the Docker setup here, or should this be closed?

**Comment by lakhujanivijay** [comment]
@fedde-s Thanks for the reply. We can close this one
