### ISSUE TITLE
Cannot launch cbioportal: Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by lakhujanivijay** [thehyve/cbioportal-docker#63]
I was successfully able to install cbioportal with docker and also, I was able to upload few data. Today I re-started the machine and to my surprise I cannot no longer launch cBioPortal. When I run below command, I ran into following issue

```
bioinfo@bioinfo-pc:$docker start cbioportal-container
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/media/bioinfo/DATA11/08_cbioportal-setup/00_cbioportal_setup/portal.properties\\\" to rootfs \\\"/var/lib/docker/overlay2/9a3af2423e5b8bcb26aeebfd31892d89d05a5fb6882b7d821a18eff55f8eae66/merged\\\" at \\\"/var/lib/docker/overlay2/9a3af2423e5b8bcb26aeebfd31892d89d05a5fb6882b7d821a18eff55f8eae66/merged/cbioportal/portal.properties\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: cbioportal-container
```

I can see the container though:

```
bioinfo@bioinfo-pc:$ docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                        PORTS                    NAMES
5684b649150c        thehyve/cbioportal:v2.0.1-iss5758   "catalina.sh run"        3 days ago          Exited (127) 15 minutes ago   0.0.0.0:8081->8080/tcp   cbioportal-container
19daf67c7aa9        mysql:5.7                           "docker-entrypoint.s…"   3 days ago          Exited (127) 15 minutes ago   3306/tcp, 33060/tcp      cbioDB

```

Could you please help?

**Comment by fedde-s** [comment]
I suspect that this is not a bug in the setup documented here. The error suggests that you configured it to use a portal.properties file that does not exist, or that is a directory/folder instead of a text file.

Also, there's generally no need to keep restarting the same container. If the existence of the portal.properties file is not the issue here, try removing the container and starting a clean one in its place.

**Comment by lakhujanivijay** [comment]
I also noticed that there is no drive called `DATA11` on my machine as shown in the path (in error)
`/media/bioinfo/DATA11/08_cbioportal-setup/00_cbioportal_setup/portal.properties` 

instead the correct path where portal.properties is lying is `/media/bioinfo/DATA1/08_cbioportal-setup/00_cbioportal_setup/portal.properties` 

I don't know where this drive name came from ?

**Comment by lakhujanivijay** [comment]
https://github.com/thehyve/cbioportal-docker/issues/63#issuecomment-496138629

Does that mean , re-installation of the whole thing from scratch once again? or just executing few steps. Can you please clarify the steps?

**Comment by fedde-s** [comment]
> I don't know where this drive name came from ?

You'd have specified that path in a `-v` argument of your `docker run` command. See [step 6 of the README](https://github.com/thehyve/cbioportal-docker/blob/v2.1.1%2Bbackport6012/README.md#step-6---run-the-cbioportal-web-server).

**Comment by lakhujanivijay** [comment]
My command was this
```

docker run -d --restart=always \
    --name=cbioportal-container \
    --net=cbio-net \
    -v $PWD'/portal.properties':/cbioportal/portal.properties:ro \
    -e CATALINA_OPTS='-Xms2g -Xmx4g' \
    -p 8081:8080 \
    thehyve/cbioportal:v2.0.1-iss5758
```

**Comment by fedde-s** [comment]
> Can you please clarify the steps?

Just the container(s): run a `docker rm` with the name of the container and then repeat the `docker run` command with all arguments, instead of using `docker stop` and `docker start`.

**Comment by fedde-s** [comment]
> My command was this

That suggests that your `$PWD` does not contain a text file named portal.properties. That' you're not running the command from the folder that contains your configuration file.

**Comment by lakhujanivijay** [comment]
@fedde-s  Thanks for your input man! This is what resolved the case:

1. I stopped the containers `cbioportal-container` and `cbioDB`.
2. Then I removed both of them 
3. Then I ran the commands

```
docker run -d --restart=always \
    --name='cbioDB' \
    --net=cbio-net \
    -e MYSQL_ROOT_PASSWORD=P@ssword1 \
    -e MYSQL_USER=cbio \
    -e MYSQL_PASSWORD=P@ssword1 \
    -e MYSQL_DATABASE=cbioportal \
    -v $PWD'/cbioportal_database_files/':/var/lib/mysql/ \
    -v $PWD'/cgds.sql':/docker-entrypoint-initdb.d/cgds.sql:ro \
    -v $PWD'/seed-cbioportal_hg19_v2.7.3.sql.gz':/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
    mysql:5.7
```
and 

```
docker run -d --restart=always \
    --name=cbioportal-container \
    --net=cbio-net \
    -v $PWD'/portal.properties':/cbioportal/portal.properties:ro \
    -e CATALINA_OPTS='-Xms2g -Xmx4g' \
    -p 8081:8080 \
    thehyve/cbioportal:v2.0.1-iss5758
```
and then re-started the containers

Thanks for your patience and support. Highly appreciated :+1:
