### ISSUE TITLE
log in for group comparison 

### ISSUE THREAD

**Issue by kcourtet** [thehyve/cbioportal-docker#69]
Hi,

I updated my docker instance to the release-3.0.1 and tried to use the new group comparison feature. This feature needs a user to log in first but there is no log button available on the interface. So do you have any solutions ?

Best regards
Kevin

**Comment by fedde-s** [comment]
Take a look at [the Documentation on Dockerising Keycloak alongside cBioPortal](https://github.com/cBioPortal/cbioportal/blob/v3.0.1/docs/docker/using-keycloak.md). Also consider [Using the Dockerfiles now maintained in cBioPortal itself for v3.x.x](https://github.com/cBioPortal/cbioportal/tree/v3.0.1/docs#211-docker); those are based directly on this setup here and integrate feedback from other institutes. We're in the process of testing whether they can indeed do everything this setup does.

**Comment by kcourtet** [comment]
I followed the steps on the Keycloak documentation but wasn't able to get the redirection page at the end (got an http status 404). It seems that some details are missing (https://github.com/thehyve/cbioportal-docker/issues/60) , I keep trying to find a solution.

**Comment by kcourtet** [comment]
Finally I managed to log in, and was able to use the new feature properly.
Thank for the support !
