### ISSUE TITLE
use jitpack solution for cbioportal artifacts

### ISSUE THREAD

**Issue by pieterlukasse** [thehyve/cbioportal-docker#7]
With Ino's jitpack solution for the project artifacts  download (PR #1798) we could even skip git, maven and building altogether!

**Comment by fedde-s** [comment]
I don't understand how you would change configuration then. Is the solution to specify properties in an environment variable at runtime instead of a `portal.properties` file at build time documented yet?

**Comment by fedde-s** [comment]
Or is this what war overlays (a concept I am not familiar with) are used for?

**Comment by pieterlukasse** [comment]
yes, we still need some extra changes to change configurations, like https://github.com/cBioPortal/cbioportal/pull/1701

**Comment by fedde-s** [comment]
If that pull request does what it looks like (the commit and PR messages are rather minimal about why it exists), that would be a huge step in cBioPortal's usability for deployers and developers!

**Comment by pieterlukasse** [comment]
with multistage docker and ready to use docker images on dockerhub, this ticket has become obsolete.
